config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  get '/add-new-transaction', to: 'transactions#new', as: 'new_transaction'
  post '/add-new-transaction', to: 'transactions#create', as: 'transactions'
  get '/wallet', to: 'wallets#show', as: 'show_wallet'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    validates :fiat_currency, presence: true
    validates :fiat_value, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validates :crypto_currency, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def new
        @transaction = Transaction.new
    end

    def create
        response = Transactions::CreateService.execute(transaction_params)

        @transaction = response[:transaction]
        
        return render :new if response[:status] == :error
        redirect_to show_wallet_url, notice: response[:notice]
    end
    
    private

    def transaction_params
        params.require(:transaction).permit(:crypto_price, :crypto_currency, :fiat_value, :fiat_currency)
    end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
    def show
        response = Wallets::ShowService.execute

        @transactions = response[:transactions]
        @current_price = response[:current_price]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_helper.rb
module CryptoHelper
    def crypto_balance(transactions, crypto)
        balance = transactions
            .select{|item| item.crypto_currency === crypto}
            .reduce(0) {|sum, item| sum + (item.fiat_value / item.crypto_price)}

        balance.round(8)
    end

    def crypto_current_price(current_price, crypto, format = true)
        response = current_price.find{|item| item['symbol'] == crypto}

        return 0 if response.nil?

        format ? number_to_currency(response['priceUsd']) : BigDecimal(response['priceUsd'])
    end
end

app/helpers/fiat_helper.rb
module FiatHelper
    include CryptoHelper

    def fiat_balance(current_price, transactions, format = true)
        response = 0

        CRYPTO_CURRENCIES.each do |crypto|
            balance = crypto_balance(transactions, crypto)
            crypto_price = crypto_current_price(current_price, crypto, false)

            response += balance * crypto_price
        end

        format ? number_to_currency(response) : BigDecimal(response)
    end

    def fiat_invested_balance(current_price, transactions, format = true)
        response = 0

        transactions.each do |transaction|
            response += transaction.fiat_value
        end

        format ? number_to_currency(response) : BigDecimal(response)
    end

    def fiat_variation(current_price, transactions)
        balance = fiat_balance(current_price, transactions, false)
        invested_balance = fiat_invested_balance(current_price, transactions, false)
        variation = ((balance - invested_balance) / invested_balance) * 100
        
        "#{variation.round(2)}%"
    end
end

app/views/home/index.html.erb
<div class="container container--center">
    <div>
        <h1><%= image_tag "logo.png", width: 240, alt: "Fuzzy Trader" %></h1>

        <p>Welcome to the best tool for new investors in cryptocurrencies.</p>

        <a href="<%= new_transaction_url %>" class="button">Add new transaction</a>
        <a href="<%= show_wallet_url %>" class="button">Show my wallet</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fuzzy Trader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert--info">
        <%= msg %>
    </div>
<% end %>

app/views/transactions/new.html.erb
<div class="container">
<%= simple_form_for(@transaction) do |f| %>
    <h1>Add new transaction</h1>
    <div class="question">
        <p>I want to invest</p>
        <div class="question__fiat">
            <%= f.input :fiat_value, label: false, as: :string %>
            <%= f.input :fiat_currency, as: :select, label: false, collection: FIAT_CURRENCIES, default: "BRL" %>
        </div>
        <p>in...</p>
        <%= f.input :crypto_currency, label: false, as: :radio_buttons, collection: CRYPTO_CURRENCIES %>
    </div>
    <button type="submit" class="button">Add transaction</button>
    <a href="<%= url_for root_path %>" class="button button--flat">Back</a>
<% end %>
</div>

app/views/wallets/show.html.erb
<div class="container">
    <h1>Your wallet</h1>
    <%= render partial: "shared/alert" %>
    <% CRYPTO_CURRENCIES.each do |crypto| %>
        <div class="crypto">
            <p>
                <strong><%= image_tag "#{crypto.downcase}.png" %> <%= crypto_balance(@transactions, crypto) %> <%= crypto %> </strong>
                <em>Current price: <%= crypto_current_price(@current_price, crypto) %> USD</em>
            </p>
        </div>
    <% end %>
    <p>Your invested balance: <strong><%= fiat_invested_balance(@current_price, @transactions) %> USD</strong></p>
    <p>Your current balance: <strong><%= fiat_balance(@current_price, @transactions) %> USD (<%= fiat_variation(@current_price, @transactions)%>)</strong></p>
    <a href="<%= url_for root_path %>" class="button button--flat">Back</a>
</div>